version: "3.9"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    networks:
      - app-network
    environment:
      - FASTAPI_URL=http://fastapi:8000

networks:
  app-network:
    driver: bridge